version: '3'
services:
  kafka:
    container_name: kafka
    hostname: kafka
    image: spotify/kafka
    environment:
      ADVERTISED_HOST: localhost
      ADVERTISED_PORT: 9092
    ports:
      - 9092:9092
